{
    "config": {
        "error": {
            "cannot_connect": "\uc5f0\uacb0\ud558\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4",
            "invalid_api_key": "API \ud0a4\uac00 \uc798\ubabb\ub418\uc5c8\uc2b5\ub2c8\ub2e4"
        },
        "step": {
            "user": {
                "data": {
                    "api_key": "API \ud0a4",
                    "name": "\uc774\ub984",
                    "url": "URL \uc8fc\uc18c"
                }
            }
        }
    }
}